import { FIELD_TYPES, OPERATORS } from "./types.js";
import type { FieldType, Operator } from "./types.js";

const EQUALS_FIELDS: FieldType[] = [
  FIELD_TYPES.STRING,
  FIELD_TYPES.NUMBER,
  FIELD_TYPES.BOOLEAN,
  FIELD_TYPES.DATE,
  FIELD_TYPES.DATE_UNIX,
];
const COMPARISON_FIELDS: FieldType[] = [
  FIELD_TYPES.NUMBER,
  FIELD_TYPES.DATE,
  FIELD_TYPES.DATE_UNIX,
];
const ARRAY_FIELDS: FieldType[] = [FIELD_TYPES.STRING, FIELD_TYPES.NUMBER];
const STRING_FIELDS: FieldType[] = [FIELD_TYPES.STRING];
const ALL_FIELDS: FieldType[] = [
  FIELD_TYPES.STRING,
  FIELD_TYPES.NUMBER,
  FIELD_TYPES.BOOLEAN,
  FIELD_TYPES.DATE,
  FIELD_TYPES.DATE_UNIX,
];

export const OPERATOR_FIELD_TYPE_MATRIX: Record<
  Operator,
  readonly FieldType[]
> = {
  [OPERATORS.EQUALS]: EQUALS_FIELDS,
  [OPERATORS.NOT_EQUALS]: EQUALS_FIELDS,
  [OPERATORS.GREATER_THAN]: COMPARISON_FIELDS,
  [OPERATORS.GREATER_THAN_OR_EQUAL_TO]: COMPARISON_FIELDS,
  [OPERATORS.LESS_THAN]: COMPARISON_FIELDS,
  [OPERATORS.LESS_THAN_OR_EQUAL_TO]: COMPARISON_FIELDS,
  [OPERATORS.IN]: ARRAY_FIELDS,
  [OPERATORS.NOT_IN]: ARRAY_FIELDS,
  [OPERATORS.CONTAINS]: STRING_FIELDS,
  [OPERATORS.NOT_CONTAINS]: STRING_FIELDS,
  [OPERATORS.STARTS_WITH]: STRING_FIELDS,
  [OPERATORS.ENDS_WITH]: STRING_FIELDS,
  [OPERATORS.EXISTS]: ALL_FIELDS,
  [OPERATORS.NOT_EXISTS]: ALL_FIELDS,
};

export function isOperatorAllowedForFieldType(
  operator: Operator,
  fieldType: FieldType,
): boolean {
  const allowed = OPERATOR_FIELD_TYPE_MATRIX[operator];
  return allowed.includes(fieldType);
}
